# Generated by Django 4.2.4 on 2023-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
