# Generated by Django 4.2.4 on 2023-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_groupuser_member_alter_messagegroup_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
