# Generated by Django 4.2.4 on 2023-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='string',
            field=models.CharField(default='0jCXnT5Msm', editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='messagegroup',
            index=models.Index(fields=['group'], name='chat_messag_group_i_625459_idx'),
        ),
    ]
