# Generated by Django 4.2.4 on 2023-09-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_messagegroup_chat_messag_group_i_625459_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invite',
            name='string',
            field=models.CharField(default='IEPnFSq7r7', editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='groupuser',
            index=models.Index(fields=['member', 'group'], name='chat_groupu_member__977e4c_idx'),
        ),
    ]
