# Generated by Django 4.2.4 on 2023-09-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_groupuser_unique_together_alter_invite_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='string',
            field=models.CharField(default='d2Rna4aDUt', editable=False, max_length=10, unique=True),
        ),
    ]
