# Generated by Django 4.2.4 on 2023-09-30 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_alter_invite_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='string',
            field=models.CharField(default='jlIOksn9vU', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group', 'member')},
        ),
    ]
